from abc import ABC,abstractmethod
class DeviceAdapter(ABC):
 @abstractmethod
 def capability_check(self):...
 @abstractmethod
 def collect_configuration(self):...
 @abstractmethod
 def backup(self):...
 @abstractmethod
 def execute(self,commands):...
 @abstractmethod
 def health_check(self):...
